/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Clases.*;
import Controlador.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Web Master
 */
public class Vista extends javax.swing.JFrame {
 CtPlan CtPlan;

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.CtPlan = new CtPlan();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelPlan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        precio_plan = new javax.swing.JComboBox<>();
        plan_nombre = new javax.swing.JComboBox<>();
        codigo_plan = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));
        btn_crearPlan = new javax.swing.JButton();
        btn_actualizarPlan1 = new javax.swing.JButton();
        btn_ConsultarPlan1 = new javax.swing.JButton();
        btn_eliminarPlan1 = new javax.swing.JButton();
        Limpiar_plan = new javax.swing.JButton();
        jPanelCliente = new javax.swing.JPanel();
        jPanelMascota = new javax.swing.JPanel();
        jPanelPago = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 255));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setAlignmentX(6.0F);
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Strawford Black", 0, 14)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(500, 129));
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(600, 300));

        jPanelPlan.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio");

        precio_plan.setBackground(new java.awt.Color(204, 204, 255));
        precio_plan.setForeground(new java.awt.Color(255, 255, 255));
        precio_plan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50.000", "90.000", "150.000", "200.000" }));
        precio_plan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_planActionPerformed(evt);
            }
        });

        plan_nombre.setBackground(new java.awt.Color(204, 204, 255));
        plan_nombre.setForeground(new java.awt.Color(255, 255, 255));
        plan_nombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bienestar", "Pro\t", "Extra", "Plus" }));
        plan_nombre.setBorder(null);
        plan_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plan_nombreActionPerformed(evt);
            }
        });

        btn_crearPlan.setBackground(new java.awt.Color(153, 153, 255));
        btn_crearPlan.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btn_crearPlan.setForeground(new java.awt.Color(255, 255, 255));
        btn_crearPlan.setText("Crear");
        btn_crearPlan.setBorder(null);
        btn_crearPlan.setBorderPainted(false);
        btn_crearPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearPlanActionPerformed(evt);
            }
        });

        btn_actualizarPlan1.setBackground(new java.awt.Color(153, 153, 255));
        btn_actualizarPlan1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btn_actualizarPlan1.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizarPlan1.setText("Actualizar");
        btn_actualizarPlan1.setBorder(null);
        btn_actualizarPlan1.setBorderPainted(false);
        btn_actualizarPlan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarPlan1ActionPerformed(evt);
            }
        });

        btn_ConsultarPlan1.setBackground(new java.awt.Color(153, 153, 255));
        btn_ConsultarPlan1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btn_ConsultarPlan1.setForeground(new java.awt.Color(255, 255, 255));
        btn_ConsultarPlan1.setText("Consultar");
        btn_ConsultarPlan1.setBorder(null);
        btn_ConsultarPlan1.setBorderPainted(false);
        btn_ConsultarPlan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarPlanActionPerformed(evt);
            }
        });

        btn_eliminarPlan1.setBackground(new java.awt.Color(153, 153, 255));
        btn_eliminarPlan1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        btn_eliminarPlan1.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminarPlan1.setText("Eliminar");
        btn_eliminarPlan1.setBorder(null);
        btn_eliminarPlan1.setBorderPainted(false);
        btn_eliminarPlan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarPlan1ActionPerformed(evt);
            }
        });

        Limpiar_plan.setBackground(new java.awt.Color(153, 153, 255));
        Limpiar_plan.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        Limpiar_plan.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar_plan.setText("Limpiar");
        Limpiar_plan.setBorder(null);
        Limpiar_plan.setBorderPainted(false);
        Limpiar_plan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_planActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPlanLayout = new javax.swing.GroupLayout(jPanelPlan);
        jPanelPlan.setLayout(jPanelPlanLayout);
        jPanelPlanLayout.setHorizontalGroup(
            jPanelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPlanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPlanLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_crearPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ConsultarPlan1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_actualizarPlan1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btn_eliminarPlan1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Limpiar_plan, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(jPanelPlanLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jPanelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(codigo_plan)
                    .addComponent(plan_nombre, 0, 105, Short.MAX_VALUE)
                    .addComponent(precio_plan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPlanLayout.setVerticalGroup(
            jPanelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPlanLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigo_plan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(plan_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precio_plan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_actualizarPlan1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(btn_ConsultarPlan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_crearPlan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_eliminarPlan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Limpiar_plan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );

        jTabbedPane1.addTab("Plan", jPanelPlan);

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cliente", jPanelCliente);

        javax.swing.GroupLayout jPanelMascotaLayout = new javax.swing.GroupLayout(jPanelMascota);
        jPanelMascota.setLayout(jPanelMascotaLayout);
        jPanelMascotaLayout.setHorizontalGroup(
            jPanelMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        jPanelMascotaLayout.setVerticalGroup(
            jPanelMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mascota", jPanelMascota);

        javax.swing.GroupLayout jPanelPagoLayout = new javax.swing.GroupLayout(jPanelPago);
        jPanelPago.setLayout(jPanelPagoLayout);
        jPanelPagoLayout.setHorizontalGroup(
            jPanelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        jPanelPagoLayout.setVerticalGroup(
            jPanelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pago", jPanelPago);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precio_planActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_planActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_planActionPerformed

    private void plan_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plan_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plan_nombreActionPerformed

    private void btn_ConsultarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarPlanActionPerformed
        // TODO add your handling code here:
           String codigo = codigo_plan.getText();
        Plan P_c = new Plan(codigo);
        if(this.CtPlan.ConsultarPlan(P_c.getCodigo())){

        }else{

        }
    }//GEN-LAST:event_btn_ConsultarPlanActionPerformed

    private void Limpiar_planActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_planActionPerformed
        // TODO add your handling code here:
           codigo_plan.setText("");
        precio_plan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "50.000", "90.000", "150.000", "200.000" }));
        plan_nombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bienestar", "Pro\t", "Extra", "Plus" }));
    }//GEN-LAST:event_Limpiar_planActionPerformed

    private void btn_actualizarPlan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarPlan1ActionPerformed
        // TODO add your handling code here:
         String codigo = codigo_plan.getText();
         String plan = plan_nombre.getSelectedItem().toString();
         String precio = (String) precio_plan.getSelectedItem();
        Plan actualizarPlan = new Plan(codigo,plan, precio);
       if(this.CtPlan.ActualizarPlan(actualizarPlan.getCodigo(),actualizarPlan.getNombre(),actualizarPlan.getPrecio())){
           
       }else{
       }
    }//GEN-LAST:event_btn_actualizarPlan1ActionPerformed

    private void btn_crearPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearPlanActionPerformed
        // TODO add your handling code here:
               String codigo = codigo_plan.getText();
        String plan = plan_nombre.getSelectedItem().toString();
        String precio = (String) precio_plan.getSelectedItem();
        Plan p = new Plan(codigo,plan,precio);
   
        if(this.CtPlan.CrearPlan(p)){
        
        }
        else{
        }
        
    }//GEN-LAST:event_btn_crearPlanActionPerformed

    private void btn_eliminarPlan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarPlan1ActionPerformed
        // TODO add your handling code here:
         String codigo = codigo_plan.getText();
       Plan E_p = new Plan(codigo);
       if(this.CtPlan.EliminarPlan(E_p.getCodigo())){
         
       }else{
            JOptionPane.showMessageDialog(null,"Su plan ha sido eliminado");
       }
        
    }//GEN-LAST:event_btn_eliminarPlan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar_plan;
    private javax.swing.JButton btn_ConsultarPlan1;
    private javax.swing.JButton btn_actualizarPlan1;
    private javax.swing.JButton btn_crearPlan;
    private javax.swing.JButton btn_eliminarPlan1;
    private javax.swing.JTextField codigo_plan;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelMascota;
    private javax.swing.JPanel jPanelPago;
    private javax.swing.JPanel jPanelPlan;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> plan_nombre;
    private javax.swing.JComboBox<String> precio_plan;
    // End of variables declaration//GEN-END:variables
}
